# Generated by Django 5.0 on 2023-12-29 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiddo_app", "0002_pais_rename_phonenum_registereduser_telefono_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registereduser",
            name="pais_origen_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kiddo_app.pais",
                verbose_name="País de origen",
            ),
        ),
    ]
