# Generated by Django 5.0 on 2024-01-04 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiddo_app", "0003_alter_registereduser_pais_origen_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tienda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("ciudad", models.CharField(max_length=100)),
                ("descripcion", models.CharField(max_length=100)),
            ],
            options={"verbose_name": "Tienda", "verbose_name_plural": "Tiendas",},
        ),
        migrations.CreateModel(
            name="TipoTienda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "TipoTienda",
                "verbose_name_plural": "Tipos_Tienda",
            },
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dia_evento", models.DateField(blank=True, null=True)),
                ("gratis", models.BooleanField()),
                ("cuota_participacion", models.IntegerField()),
                (
                    "pais_origen_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kiddo_app.pais",
                        verbose_name="País de origen",
                    ),
                ),
                (
                    "patrocinante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kiddo_app.registereduser",
                        verbose_name="liente_id",
                    ),
                ),
                (
                    "tienda_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kiddo_app.tienda",
                        verbose_name="Tienda",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="registereduser",
            name="tienda_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kiddo_app.tienda",
                verbose_name="Tiendas",
            ),
        ),
        migrations.AddField(
            model_name="tienda",
            name="tipo_de_tienda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kiddo_app.tipotienda",
                verbose_name="TipoTienda",
            ),
        ),
    ]
