# Generated by Django 5.0 on 2024-01-08 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "kiddo_app",
            "0004_tienda_tipotienda_evento_registereduser_tienda_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="registereduser",
            name="dueño_tienda",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="evento",
            name="patrocinante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kiddo_app.registereduser",
                verbose_name="Patrocinante",
            ),
        ),
    ]
